name: AI Code Review

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AI_REVIEW_MODEL: ${{ vars.AI_REVIEW_MODEL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Skip AI review when API key is missing
        if: env.OPENAI_API_KEY == ''
        run: echo "::warning::OPENAI_API_KEY secret is not configured. Skipping AI review."

      - name: Set up Python
        if: env.OPENAI_API_KEY != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AI review dependencies
        if: env.OPENAI_API_KEY != ''
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.1

      - name: Run AI code review
        if: env.OPENAI_API_KEY != ''
        run: python ci/ai_review.py
